#!/usr/bin/env python3
"""Refresh data/candidates.js and data/wards.js.

Candidates come from the list embedded at
https://mississaugavotes.ca/2026-municipal-election/for-voters/whos-running/
(served by ovs.voterview.ca). Ward polygons come from Mississauga Open Data.
"""
import html
import json
import re
import urllib.request
from pathlib import Path

CANDIDATES_URL = "https://ovs.voterview.ca/candidateList/candidatedetails?filter=&countyMun=2105&schoolcode="
WARDS_URL = (
    "https://services6.arcgis.com/hM5ymMLbxIyWTjn2/arcgis/rest/services/Ward_Boundaries/"
    "FeatureServer/2/query?where=1%3D1&outFields=WARD&outSR=4326&f=geojson"
    "&geometryPrecision=5&maxAllowableOffset=0.0001"
)
DATA = Path(__file__).resolve().parent.parent / "data"


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    return urllib.request.urlopen(req, timeout=60).read().decode("utf-8")


def parse_candidates(page):
    page = re.sub(r'<a [^>]*href="mailto:([^"]+)"[^>]*>', r"\nEMAIL:\1\n", page)
    text = html.unescape(re.sub(r"<[^>]+>", "\n", page))
    lines = [l.strip() for l in text.split("\n") if l.strip()]

    races, race, cur = {}, None, None
    for i, line in enumerate(lines):
        nxt = lines[i + 1] if i + 1 < len(lines) else ""
        if line == "Candidates for":
            race, cur = nxt, None
            races[race] = []
        elif race and line.isupper() and nxt in ("Acclaimed", "+"):
            cur = {"name": re.sub(r"\s+", " ", line).title(), "email": None}
            races[race].append(cur)
        elif race and cur and line.startswith("EMAIL:") and not cur["email"]:
            cur["email"] = line[6:].strip().lower()

    out = {"mayor": [], "wards": {}}
    for race, people in races.items():
        if "Mayor" in race:
            out["mayor"] = people
        m = re.fullmatch(r"Councillor Ward (\d+)", race)
        if m:
            out["wards"][m.group(1)] = people
    return out


def main():
    DATA.mkdir(exist_ok=True)
    candidates = parse_candidates(get(CANDIDATES_URL))
    (DATA / "candidates.js").write_text(
        "// Generated by scripts/update_data.py from mississaugavotes.ca (Who's running)\n"
        "window.CANDIDATES = " + json.dumps(candidates, indent=1) + ";\n"
    )
    wards = json.loads(get(WARDS_URL))
    (DATA / "wards.js").write_text(
        "// Generated by scripts/update_data.py from Mississauga Open Data (Ward Boundaries)\n"
        "window.WARDS = " + json.dumps(wards, separators=(",", ":")) + ";\n"
    )
    print("wards:", {k: len(v) for k, v in candidates["wards"].items()}, "mayor:", len(candidates["mayor"]))


if __name__ == "__main__":
    main()
